/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package loudest_mindset.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import java.time.OffsetDateTime;

/**
 * Comment
 */
@Entity
public class Comment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @JsonProperty("id")
    private Long id = null;

    @JsonProperty("userId")
    private Long userId = null;

    @JsonProperty("shoutId")
    private Long shoutId = null;

    @JsonProperty("text")
    private String text = null;

    @JsonProperty("timestamp")
    private OffsetDateTime timestamp = null;

    public Comment id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * auto generated by ORM or DBMS
     *
     * @return id
   *
     */


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Comment userId(Long userId) {
        this.userId = userId;
        return this;
    }

    /**
     * id of the creator
     *
     * @return userId
   *
     */


    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Comment shoutId(Long shoutId) {
        this.shoutId = shoutId;
        return this;
    }

    /**
     * shoutId of the corresponding shout
     *
     * @return shoutId
   *
     */


    public Long getShoutId() {
        return shoutId;
    }

    public void setShoutId(Long shoutId) {
        this.shoutId = shoutId;
    }

    public Comment text(String text) {
        this.text = text;
        return this;
    }

    /**
     * content of the shout
     *
     * @return text
   *
     */


    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Comment timestamp(OffsetDateTime timestamp) {
        this.timestamp = timestamp;
        return this;
    }

    /**
     * timestamp in ISO 8601 format
     *
     * @return timestamp
   *
     */

    public OffsetDateTime getTimestamp() {
        return timestamp;
    }

    public void setTimestamp() {
        this.timestamp = OffsetDateTime.now();
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Comment comment = (Comment) o;
        return Objects.equals(this.id, comment.id)
                && Objects.equals(this.userId, comment.userId)
                && Objects.equals(this.shoutId, comment.shoutId)
                && Objects.equals(this.text, comment.text)
                && Objects.equals(this.timestamp, comment.timestamp);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, userId, shoutId, text, timestamp);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Comment {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
        sb.append("    shoutId: ").append(toIndentedString(shoutId)).append("\n");
        sb.append("    text: ").append(toIndentedString(text)).append("\n");
        sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
