/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package loudest_mindset.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;

/**
 * Listening
 */
@Entity
public class Listening {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @JsonProperty("id")
    private Long id = null;

    @JsonProperty("senderId")
    private Long senderId = null;

    @JsonProperty("receiverId")
    private Long receiverId = null;

    /**
     * auto generated by ORM or DBMS
     *
     * @return id
     *
     */
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Listening senderId(Long senderId) {
        this.senderId = senderId;
        return this;
    }

    /**
     * id of the sender
     *
     * @return senderId
   *
     */
    public Long getSenderId() {
        return senderId;
    }

    public void setSenderId(Long senderId) {
        this.senderId = senderId;
    }

    public Listening receiverId(Long receiverId) {
        this.receiverId = receiverId;
        return this;
    }

    /**
     * id of the one who is listening
     *
     * @return receiverId
   *
     */
    public Long getReceiverId() {
        return receiverId;
    }

    public void setReceiverId(Long receiverId) {
        this.receiverId = receiverId;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Listening listening = (Listening) o;
        return Objects.equals(this.senderId, listening.senderId)
                && Objects.equals(this.receiverId, listening.receiverId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(senderId, receiverId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Listening {\n");

        sb.append("    senderId: ").append(toIndentedString(senderId)).append("\n");
        sb.append("    receiverId: ").append(toIndentedString(receiverId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
