/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package loudest_mindset.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import java.time.OffsetDateTime;

/**
 * Message
 */
@Entity
public class Message {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @JsonProperty("id")
    private Long id = null;
    
    @JsonProperty("senderId")
    private Long senderId = null;

    @JsonProperty("receiverId")
    private Long receiverId = null;

    @JsonProperty("text")
    private String text = null;

    @JsonProperty("timestamp")
    private OffsetDateTime timestamp = null;

    public Message senderId(Long senderId) {
        this.senderId = senderId;
        return this;
    }

        /**
     * auto generated by ORM or DBMS
     *
     * @return id
   *
     */
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    /**
     * id of the sender
     *
     * @return senderId
   *
     */
    public Long getSenderId() {
        return senderId;
    }

    public void setSenderId(Long senderId) {
        this.senderId = senderId;
    }

    public Message receiverId(Long receiverId) {
        this.receiverId = receiverId;
        return this;
    }

    /**
     * id of the receiver
     *
     * @return receiverId
   *
     */
    public Long getReceiverId() {
        return receiverId;
    }

    public void setReceiverId(Long receiverId) {
        this.receiverId = receiverId;
    }

    public Message text(String text) {
        this.text = text;
        return this;
    }

    /**
     * content of the message
     *
     * @return text
   *
     */
    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Message timestamp(OffsetDateTime timestamp) {
        this.timestamp = timestamp;
        return this;
    }

    /**
     * timestamp in ISO 8601 format
     *
     * @return timestamp
   *
     */
    public OffsetDateTime getTimestamp() {
        return timestamp;
    }

    public void setTimestamp() {
        this.timestamp = OffsetDateTime.now();
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Message message = (Message) o;
        return Objects.equals(this.senderId, message.senderId)
                && Objects.equals(this.receiverId, message.receiverId)
                && Objects.equals(this.text, message.text)
                && Objects.equals(this.timestamp, message.timestamp);
    }

    @Override
    public int hashCode() {
        return Objects.hash(senderId, receiverId, text, timestamp);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Message {\n");

        sb.append("    senderId: ").append(toIndentedString(senderId)).append("\n");
        sb.append("    receiverId: ").append(toIndentedString(receiverId)).append("\n");
        sb.append("    text: ").append(toIndentedString(text)).append("\n");
        sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
